Portfolio-finish-mobile-version
OTMANE-ECHCHAFYKY/Portfolio-mobile-version pull request #2
Opened 2023-03-24 13:44 UTC by OTMANE-ECHCHAFYKY

- [ ] Add Projects section to HTML.
- [ ] Add styles to the Projects section

2023-03-24 14:53 UTC, amon-cofie requested changes
Hi @OTMANE-ECHCHAFYKY , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

## Highlights
🚀 Linters are passing 
🚀 Good commit messages

## Required Changes ♻️

Perhaps you forgot 😅 but please add the about section as stated in the project requirements 👍 
You have done such a great job on the works section that I doubt you would have much problems adding the about section 😉 
![image](https://user-images.githubusercontent.com/107795045/227556915-98cc49cf-1f02-4111-a96a-f951a6fe2895.png)



_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 14:53 UTC, amon-cofie commented on index.html
> +        </div>
This section is very well done but there are a few things that you can add to make it even perfect and identical to the Figma design completely. I suggest you check the spacing around these parts of the section as shown in the image below. They are wider than it is in the Figma design 😉 

Your design: 
![image](https://user-images.githubusercontent.com/107795045/227558715-6f51ec83-a888-4f3b-9b94-dbcc26c48e02.png)

Figma design: 
![image](https://user-images.githubusercontent.com/107795045/227558972-5b316ba7-8181-42f3-ab3c-4ccb5324ca7a.png)

2023-03-25 10:42 UTC, Kamba56 requested changes
Hi @OTMANE-ECHCHAFYKY, 

Great work on making the changes requested by a previous reviewer 👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [x] Great use of Github workflow!👏👏👏
- [x] All linters passed!👏👏👏
- [ ] Great job adding the work and about section

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 10:42 UTC, Kamba56 commented on index.html
>    </body>
- [ ] Great job adding the about section. Kindly add the background image in the about section to match the figma template. You are expected to stick to design as much as possible including the background images.
### your design
![image](https://user-images.githubusercontent.com/94551484/227712173-f541f333-7855-49b5-ac06-09ab84fc9aaa.png)
### Figma
![image](https://user-images.githubusercontent.com/94551484/227712208-d0d4f9c9-c490-40ed-aacc-0a1caf5e4b5d.png)

2023-03-25 10:42 UTC, Kamba56 commented on style.css
- [Optional] As demanded by the project requirements, kindly lay out the container of your work cards using CSS grid and the contents of each card using CSS flexbox. this Is because grid and flexbox are great for responsive design.

2023-03-25 10:55 UTC, OTMANE-ECHCHAFYKY commented on style.css
I used them both

2023-03-25 12:24 UTC, Tufahel approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

Hi @OTMANE-ECHCHAFYKY  :wave: 
 
Your project is complete now!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 👏🏻

![](https://media0.giphy.com/media/d31w24psGYeekCZy/giphy.gif?cid=ecf05e47zaer8jfqmid0gfxhz2oq4gcjqy2c2aol3ldn6gvl&rid=giphy.gif&ct=g)

:heavy_check_mark: Descriptive pull request.
:heavy_check_mark: Commit messages are professional.
:heavy_check_mark: Follow git-flow.


## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.
- You can mail me at [![Mail](https://img.shields.io/badge/Gmail-tufahel96@gmail.com-red?logo=Gmail&logoColor=red&labelColor=black)](mailto:tufahel96@gmail.com) or ask any question at Slack, `Name: Tufahel`

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 12:28 UTC, merged

2023-03-25 12:30 UTC, Kamba56 commented on style.css
> I used them both

Yes you used flexbox on both the work container and the work cards.
But the project requirements states that you put your work cards in one element and use a CSS grid to lay out that element. Let me give you an instance